export const products = [
    {
      id: 1,
      name: "Paracetamol 500mg",
      description: "Effective pain relief for headaches, toothaches, and fever reduction.",
      longDescription:
        "Paracetamol is a widely used over-the-counter pain reliever and fever reducer. It's used to treat many conditions such as headache, muscle aches, arthritis, backache, toothaches, colds, and fevers.",
      price: 5.99,
      category: "Pain Relief",
      prescription: false,
      stock: 500,
    },
    {
      id: 2,
      name: "Amoxicillin 250mg",
      description: "Antibiotic used to treat a number of bacterial infections.",
      price: 12.99,
      category: "Antibiotics",
      prescription: true,
      stock: 200,
    },
    {
      id: 3,
      name: "Vitamin D3 1000IU",
      description: "Supports bone health and immune function.",
      price: 8.49,
      category: "Vitamins",
      prescription: false,
      stock: 350,
    },
    {
      id: 4,
      name: "Ibuprofen 200mg",
      description: "Anti-inflammatory medication for pain and fever reduction.",
      price: 6.99,
      category: "Pain Relief",
      prescription: false,
      stock: 450,
    },
    {
      id: 5,
      name: "First Aid Kit Basic",
      description: "Essential supplies for treating minor injuries and emergencies.",
      price: 24.99,
      category: "First Aid",
      prescription: false,
      stock: 100,
    },
    {
      id: 6,
      name: "Cetirizine 10mg",
      description: "Antihistamine for allergy relief and hay fever symptoms.",
      price: 9.99,
      category: "Allergy",
      prescription: false,
      stock: 300,
    },
    {
      id: 7,
      name: "Cough Syrup",
      description: "Relieves cough and soothes throat irritation.",
      price: 7.49,
      category: "Cold & Flu",
      prescription: false,
      stock: 250,
    },
    {
      id: 8,
      name: "Azithromycin 500mg",
      description: "Antibiotic used to treat various bacterial infections.",
      price: 15.99,
      category: "Antibiotics",
      prescription: true,
      stock: 180,
    },
    {
      id: 9,
      name: "Multivitamin Complex",
      description: "Complete daily nutritional support with essential vitamins and minerals.",
      price: 11.99,
      category: "Vitamins",
      prescription: false,
      stock: 400,
    },
    {
      id: 10,
      name: "Bandage Roll",
      description: "Sterile bandage for wound dressing and support.",
      price: 3.99,
      category: "First Aid",
      prescription: false,
      stock: 600,
    },
  ]
  